set $backend_T1 "http://t1-controller:8081";

### T1 STATIC FILES
location ~ ^/(t1) {
    include /etc/nginx/includes/proxy.conf;
    proxy_pass $backend_T1;
}

### DASHBOARD ADMIN
location ~ ^/(dashboard|dashboard/(admins|players|suggestions))$ {
    include /etc/nginx/includes/proxy.conf;
    proxy_pass $backend_T1;
}

### OPPONENTS / CLASSES ROUTES
location ~ ^/opponents/ {
    include /etc/nginx/includes/proxy.conf;
    proxy_pass $backend_T1;
}

### TEAMS
location ~ ^/team/(main|details)$ {
    include /etc/nginx/includes/proxy.conf;
    proxy_pass $backend_T1;
}

### SCALATA
location ~ /scalata/(main) {
    include /etc/nginx/includes/proxy.conf;
    proxy_pass $backend_T1;
}

### SUGGERIMENTI (API T1)
location ~ ^/suggerimenti/ {
    include /etc/nginx/includes/proxy.conf;
    proxy_pass $backend_T1;
}
