# Url servizi
API_GATEWAY_ENDPOINT=127.0.0.1

# Porte servizi
API_GATEWAY_PORT=8090

# Configurazione MySQL in locale
MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_DATABASE=manvsclass
MYSQL_USERNAME=manvsclass_user
MYSQL_PASSWORD=manvsclass_pass
